// src/lib/components/ButtonSelector.svelte
<script type="ts">
  import Button from './Button.svelte';

  export let size: 'small' | 'large' | 'normal' = 'normal';
  export let options: { label: string; value: string }[];
  export let selected: string;
  export let onSelect: (value: string) => void;
</script>

<div class="ButtonSelector">
  {#each options as opt (opt.value)}
    <Button
      key={opt.value}
      class={selected === opt.value ? 'selected' : ''}
      {size}
      on:click={() => onSelect(opt.value)}
    >
      {opt.label}
    </Button>
  {/each}
</div>

// app/components/ButtonSelector.tsx
import Button from './Button';

type ButtonSelectorProps = {
  options: { label: string; value: string }[];
  selected: string;
  size?: 'small' | 'normal' | 'large';
  onSelect: (value: string) => void;
};

export default function ButtonSelector(props: ButtonSelectorProps) {
  const { options, size, selected, onSelect } = props;

  return (
    <div className="ButtonSelector">
      {options.map((opt) => (
        <Button
          key={opt.value}
          className={
            selected === opt.value ? 'ButtonSelector-selected' : undefined
          }
          label={opt.label}
          size={size}
          onClick={() => onSelect(opt.value)}
        />
      ))}
    </div>
  );
}
