// src/lib/components/Header.svelte
<script type="ts">
  import type { Feed } from '@prisma/client';
  import type { FeedGroupWithFeeds } from '$lib/db/feedgroup';
  import UserIcon from '$lib/icons/User.svelte';
  import RssIcon from '$lib/icons/Rss.svelte';
  import { feeds, feedGroups } from '$lib/stores';

  export let selectedFeedIds: Feed['id'][] | undefined;
  export let onTitlePress: () => void;
  export let toggleSidebar: () => void;

  $: title = getFeedsTitle($feedGroups, $feeds, selectedFeedIds);

  function getFeedsTitle(
    feedGroups: FeedGroupWithFeeds[] | undefined,
    feeds: Feed[] | undefined,
    selectedFeedIds: string[] | undefined
  ): string {
    if (
      !selectedFeedIds ||
      selectedFeedIds.length === 0 ||
      !feeds ||
      !feedGroups
    ) {
      return '';
    }

    if (selectedFeedIds.length === 1) {
      for (const feed of feeds) {
        if (feed.id === selectedFeedIds[0]) {
          return feed.title;
        }
      }
    } else if (selectedFeedIds.length > 1) {
      for (const group of feedGroups) {
        for (const groupFeed of group.feeds) {
          if (groupFeed.feedId === selectedFeedIds[0]) {
            return group.name;
          }
        }
      }
    }

    return '';
  }
</script>

<header class="header">
  <div class="left" on:click={toggleSidebar}>
    <RssIcon size="22px" />
    <h1>Simple News</h1>
  </div>
  <div class="center">
    <h2 on:click={onTitlePress}>{title}</h2>
  </div>
  <div class="right">
    <a class="user" href="/auth/logout">
      <UserIcon size={20} />
    </a>
  </div>
</header>

<style>
  .header {
    display: grid;
    grid-template-columns: min-content 1fr min-content;
    align-items: center;
    border-bottom: solid 1px var(--border);
    user-select: none;
    -webkit-user-select: none;
  }

  .left {
    display: flex;
    align-items: center;
    padding: calc(var(--side-pad) / 2) var(--side-pad);
    gap: 0.25rem;
    cursor: pointer;
  }

  .left h1 {
    margin: 0;
    padding: 0;
    font-size: calc(var(--font-size) * 1.25);
    white-space: nowrap;
  }

  .center {
    justify-content: center;
    display: flex;
    flex-direction: row;
    overflow: hidden;
    gap: 0.5rem;
  }

  .center h2 {
    font-size: var(--font-size);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    margin: 0;
    cursor: pointer;
  }

  .right {
    justify-self: right;
    padding: calc(var(--side-pad) / 2) var(--side-pad);
  }

  .user {
    cursor: pointer;
    text-decoration: none;
    color: inherit;
    display: flex;
    align-items: center;
  }

  /* Mobile */
  @media only screen and (max-width: 800px) {
    h1 {
      display: none;
    }
  }
</style>

// app/components/Header.tsx
import type { Feed } from '@prisma/client';
import { Link } from '@remix-run/react';
import { TbUserCircle } from 'react-icons/tb';
import { getFeedsFromUser, useUser } from '~/lib/util';
import type { FeedGroupWithFeeds } from '~/models/feedGroup.server';

type HeaderProps = {
  selectedFeedIds: string[] | undefined;
  onTitlePress: () => void;
  toggleSidebar: () => void;
};

const getFeedsTitle = (
  feedGroups: FeedGroupWithFeeds[] | undefined,
  feeds: Feed[] | undefined,
  selectedFeedIds: string[] | undefined
) => {
  if (
    !selectedFeedIds ||
    selectedFeedIds.length === 0 ||
    !feeds ||
    !feedGroups
  ) {
    return undefined;
  }

  if (selectedFeedIds.length === 1) {
    for (const feed of feeds) {
      if (feed.id === selectedFeedIds[0]) {
        return feed.title;
      }
    }
  } else if (selectedFeedIds.length > 1) {
    for (const group of feedGroups) {
      for (const groupFeed of group.feeds) {
        if (groupFeed.feed.id === selectedFeedIds[0]) {
          return group.name;
        }
      }
    }
  }

  return undefined;
};

export default function Header(props: HeaderProps) {
  const user = useUser();
  const feeds = getFeedsFromUser(user);
  const { onTitlePress, toggleSidebar, selectedFeedIds } = props;
  const title = getFeedsTitle(user.feedGroups, feeds, selectedFeedIds);

  return (
    <header className="Header">
      <div className="Header-left" onClick={toggleSidebar}>
        <svg width="22" height="22" version="2.0">
          <use href="#sn-logo" />
        </svg>
        <h1>Simple News</h1>
      </div>
      <div className="Header-center">
        <h2 onClick={onTitlePress}>{title}</h2>
      </div>
      <div className="Header-right">
        <Link className="Header-user" to="/login">
          <TbUserCircle size={20} />
        </Link>
      </div>
    </header>
  );
}
