// src/lib/components/ButtonSelector.svelte
<script type="ts">
  import Button from './Button.svelte';

  export let size: 'small' | 'large' | 'normal' = 'normal';
  export let options: { label: string; value: string }[];
  export let selected: string;
  export let onSelect: (value: string) => void;
</script>

<div class="ButtonSelector">
  {#each options as opt (opt.value)}
    <Button
      key={opt.value}
      class={selected === opt.value ? 'selected' : ''}
      {size}
      on:click={() => onSelect(opt.value)}
    >
      {opt.label}
    </Button>
  {/each}
</div>

// client/components/ButtonSelector.tsx
import React, { type FC } from "react";
import Button from "./Button.tsx";

export type ButtonSelectorProps = {
  options: { label: string; value: string }[];
  selected: string;
  size?: "small" | "normal" | "large";
  onSelect: (value: string) => void;
};

const ButtonSelector: FC<ButtonSelectorProps> = (props) => {
  const { options, size, selected, onSelect } = props;

  return (
    <div className="ButtonSelector">
      {options.map((opt) => (
        <Button
          key={opt.value}
          className={selected === opt.value
            ? "ButtonSelector-selected"
            : undefined}
          label={opt.label}
          size={size}
          onClick={() => onSelect(opt.value)}
        />
      ))}
    </div>
  );
};

export default ButtonSelector;
