// app/components/FeedsList.tsx
import type { Feed } from '@prisma/client';
import { Link } from '@remix-run/react';
import { useState } from 'react';
import {
  className,
  getFeedsFromGroup,
  getFeedsFromUser,
  useSelectedFeedIds,
} from '~/lib/util';
import type { FeedStats } from '~/models/feed.server';
import type { UserWithFeeds } from '~/models/user.server';
import type { ArticleFilter } from '~/routes/reader';

function isSelected(feeds: Feed[], selected: Feed['id'][] | undefined) {
  if (!selected) {
    return false;
  }
  return feeds.every(({ id }) => selected.includes(id));
}

function getArticleCount(
  feeds: Feed[],
  feedStats: FeedStats,
  articleFilter: ArticleFilter
): number {
  return feeds.reduce((acc, feed) => {
    const stats = feedStats[feed.id];
    return (
      acc +
      (articleFilter === 'unread' ? stats.total - stats.read : stats.total)
    );
  }, 0);
}

type FeedsProps = {
  user: UserWithFeeds;
  feedStats: FeedStats;
  articleFilter: ArticleFilter;
  onSelect?: () => void;
};

export default function Feeds(props: FeedsProps) {
  const { user, feedStats, onSelect, articleFilter } = props;
  const [expanded, setExpanded] = useState<{ [title: string]: boolean }>({});
  const feeds = getFeedsFromUser(user);
  const selectedFeedIds = useSelectedFeedIds();

  return (
    <ul className="Feeds">
      {user?.feedGroups
        .filter(
          (group) =>
            getArticleCount(
              getFeedsFromGroup(group),
              feedStats,
              articleFilter
            ) > 0
        )
        .map((group) => (
          <li
            key={group.name}
            className={className({
              'Feeds-expanded': expanded[group.name],
            })}
          >
            <div
              className={className('Feeds-group', {
                'Feeds-selected': isSelected(
                  getFeedsFromGroup(group),
                  selectedFeedIds
                ),
              })}
            >
              <span
                className="Feeds-expander"
                onClick={() =>
                  setExpanded({
                    ...expanded,
                    [group.name]: !expanded[group.name],
                  })
                }
              />
              <Link
                className="Feeds-title"
                to={`group-${group.id}`}
                onClick={() => {
                  // setSelectedFeeds(
                  //   getFeedsFromGroup(group).map(({ id }) => id)
                  // );
                  onSelect?.();
                }}
              >
                {group.name}
              </Link>
              {feedStats && (
                <span className="Feeds-unread">
                  {getArticleCount(
                    getFeedsFromGroup(group),
                    feedStats,
                    articleFilter
                  )}
                </span>
              )}
            </div>

            <ul>
              {getFeedsFromGroup(group)
                .filter(
                  (feed) =>
                    getArticleCount([feed], feedStats, articleFilter) > 0
                )
                .map((feed) => (
                  <li
                    className={className('Feeds-feed', {
                      'Feeds-selected': isSelected([feed], selectedFeedIds),
                    })}
                    key={feed.id}
                    onClick={() => {
                      onSelect?.();
                    }}
                  >
                    <Link to={`feed-${feed.id}`} className="Feeds-title">
                      {feeds?.find((f) => f.id === feed.id)?.title}
                    </Link>
                    <div className="Feeds-unread">
                      {(feedStats?.[feed.id].total ?? 0) -
                        (feedStats?.[feed.id].read ?? 0)}
                    </div>
                  </li>
                ))}
            </ul>
          </li>
        ))}
    </ul>
  );
}

// src/lib/components/FeedsList.svelte
<script type="ts">
  import type { Feed } from '@prisma/client';
  import type { FeedStats } from '$lib/db/feed';
  import type { UserWithFeeds } from '$lib/db/user';
  import type { ArticleFilter } from '$lib/types';
  import { getFeedsFromGroup, getFeedsFromUser } from '$lib/util';

  export let user: UserWithFeeds;
  export let feedStats: FeedStats;
  export let articleFilter: ArticleFilter;
  export let selectedFeedIds: Feed['id'][] | undefined;
  export let onSelect: () => void;

  let expanded: { [title: string]: boolean } = {};
  const feeds = getFeedsFromUser(user);

  function getArticleCount(
    feeds: Feed[],
    feedStats: FeedStats,
    articleFilter: ArticleFilter
  ): number {
    return feeds.reduce((acc, feed) => {
      const stats = feedStats[feed.id] ?? {};
      return (
        acc +
        (articleFilter === 'unread' ? stats.total - stats.read : stats.total)
      );
    }, 0);
  }

  function isSelected(feeds: Feed[], selected: Feed['id'][] | undefined) {
    if (!selected) {
      return false;
    }
    return feeds.every(({ id }) => selected.includes(id));
  }
</script>

<ul class="feeds">
  {#each user.feedGroups as group (group.name)}
    {#if getArticleCount(getFeedsFromGroup(group), feedStats, articleFilter) > 0}
      <li class:expanded={expanded[group.name]}>
        <div
          class="group"
          class:selected={isSelected(getFeedsFromGroup(group), selectedFeedIds)}
        >
          <span
            class="expander"
            on:click={() => {
              expanded = {
                ...expanded,
                [group.name]: !expanded[group.name]
              };
            }}
          />
          <a
            class="title"
            href={`/reader/group-${group.id}`}
            on:click={() => {
              // setSelectedFeeds(
              //   getFeedsFromGroup(group).map(({ id }) => id)
              // );
              onSelect?.();
            }}
          >
            {group.name}
          </a>
          {#if feedStats}
            <span class="Feeds-unread">
              {getArticleCount(
                getFeedsFromGroup(group),
                feedStats,
                articleFilter
              )}
            </span>
          {/if}
        </div>

        <ul>
          {#each getFeedsFromGroup(group) as feed (feed.id)}
            {#if getArticleCount([feed], feedStats, articleFilter) > 0}
              <li
                class="feed"
                class:selected={isSelected([feed], selectedFeedIds)}
                on:click={() => {
                  onSelect?.();
                }}
              >
                <a href={`reader/feed-${feed.id}`} class="title">
                  {feeds?.find((f) => f.id === feed.id)?.title}
                </a>
                <div class="unread">
                  {(feedStats?.[feed.id].total ?? 0) -
                    (feedStats?.[feed.id].read ?? 0)}
                </div>
              </li>
            {/if}
          {/each}
        </ul>
      </li>
    {/if}
  {/each}
</ul>

<style>
  .feeds {
    list-style-type: none;
    padding: 1rem;
    margin: 0;
    --hpad: 0.5rem;
    --vpad: 0.25rem;
    --expander-width: 1rem;
  }

  .selected {
    background: rgba(255, 255, 255, 0.1);
  }

  .group,
  .feed {
    border-radius: var(--border-radius);
  }

  .expanded .selected {
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
  }

  .expanded .selected:first-child {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }

  .feeds ul {
    list-style-type: none;
    padding: 0;
  }

  .feed {
    display: flex;
    flex-direction: row;
  }

  .group {
    display: flex;
    align-items: center;
  }

  .group > *,
  .feed > * {
    padding: var(--vpad) var(--hpad);
  }

  .feed {
    /* padding is size of expander + expander padding */
    padding-left: calc(var(--expander-width) + 2 * var(--hpad));
  }

  .expander::before {
    content: '▷';
    display: inline-block;
    flex-grow: 0;
    width: var(--expander-width);
  }

  .title {
    flex-grow: 1;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  a.title {
    text-decoration: none;
    color: inherit;
  }

  .group,
  .feed {
    cursor: pointer;
  }

  .feeds ul {
    display: none;
  }

  .expanded ul {
    display: initial;
  }

  .expanded .expander::before {
    content: '▽';
  }

  @media (hover: hover) {
    .group:hover,
    .feed:hover {
      background: rgba(0, 0, 0, 0.1);
    }
  }
</style>
